import rhinoscriptsyntax as rs

# user clicks on cuts and it
#  assigns which is the starting point of the line

objs = rs.ObjectsByType(8192)
if (objs):
    for obj in objs:
        item = rs.TextDotText( obj )
        if item.isdigit(): rs.DeleteObject( obj )

objs = rs.ObjectsByLayer("PARTS")
if (objs):
    for obj in objs:
        type = rs.IsUserText(obj)
        # remove old ones
        if type==1: rs.GetUserText( obj, "start_location")

objs = rs.ObjectsByLayer("CUTS")
if (objs):
    for obj in objs:
        type = rs.IsUserText(obj)
        # remove old ones
        if type==1: rs.GetUserText( obj, "start_location")

objs = rs.ObjectsByLayer("ENGRAVE")
if (objs):
    for obj in objs:
        type = rs.IsUserText(obj)
        # remove old ones
        if type==1: rs.GetUserText( obj, "start_location")
        
rs.UnselectObjects(objects)

print "HERE"
objs = rs.GetObjects("Select things")

if (objs):
    count = 1;
    for obj in objs:
        rs.SelectObject(obj)
        point = rs.GetPointOnCurve(obj, "Point on curve")
        print "SET: %d" % count
        count += 1
        # rs.SetUserText( obj, "start_location", "[%lf %lf %lf]" % (pt[0], pt[1], pt[2]))


